#!/bin/sh
# Initialize AdGuard Home configuration directories
# We use /config to map nicely to a single volume

mkdir -p /config/conf /config/work
chown -R bsd:bsd /config

echo "AdGuard Home directories initialized"